version: '3.4'

services:
  hairhub.api:
    image: ${DOCKER_REGISTRY-}hairhubapi
    networks:
      - hairhub
    ports:
      - "8080:80"
      - "443:443"
    build:
      context: .
      dockerfile: Hairhub.API/Dockerfile
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ConnectionStrings__DefaultConnection: "Server=mssql-db;Database=HairHubDB;User Id=sa;Password=Admin@123;"
      TZ: "Asia/Ho_Chi_Minh"
   # depends_on:
    #  - mssql

networks:
  hairhub:
    external: false



# version: '3.4'

# services:
#   mssql:
#     container_name: mssql-db
#     hostname: mssql-db
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     user: root
#     networks:
#       - demo
#     environment:
#       accept_eula: 'y'
#       sa_password: 'admin@123'
#       mssql_pid: 'developer'
#       mssql_tcp_port: 1433
#       tz: "asia/ho_chi_minh"
#     ports:
#       - "1455:1433"
#     volumes:
#       - mssql-data:/var/opt/mssql/data
#       - mssql-log:/var/opt/mssql/log
#       - mssql-secrets:/var/opt/mssql/secrets

#   hairhub.api:
#     image: ${docker_registry-}hairhubapi
#     networks:
#       - demo
#     ports:
#       - "8080:80"   # thay đổi cổng này thành 8080:80 nếu bạn muốn ứng dụng lắng nghe http trên cổng 8080
#       - "443:443"   # đảm bảo rằng ứng dụng cũng hỗ trợ https trên cổng 443
#     build:
#       context: .
#       dockerfile: hairhub.api/dockerfile
#     environment:
#       aspnetcore_urls: https://+:443;http://+:80  # cấu hình lắng nghe cả http và https
#       connectionstrings__defaultconnection: "server=mssql-db;database=hairhubdb;user id=sa;password=admin@123;"
#       tz: "asia/ho_chi_minh"
#     depends_on:
#       - mssql

# networks:
#   demo:
#     name: demo

# volumes:
#   mssql-data: # định nghĩa named volume 'mssql-data'
#   mssql-log: # định nghĩa named volume 'mssql-log'
#   mssql-secrets: # định nghĩa named volume 'mssql
