# version: '3.4'

# services:
#   mssql:
#     container_name: mssql-db
#     hostname: mssql-db
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     user: root
#     networks:
#       - demo
#     environment:
#       ACCEPT_EULA: 'Y'
#       SA_PASSWORD: 'Admin@123'
#       MSSQL_PID: 'Developer'
#       MSSQL_TCP_PORT: 1433
#       TZ: "Asia/Ho_Chi_Minh"
#     ports:
#       - "1455:1433"
#     volumes:
#       - mssql-data:/var/opt/mssql/data
#       - mssql-log:/var/opt/mssql/log
#       - mssql-secrets:/var/opt/mssql/secrets

#   hairhub.api:
#     image: ${DOCKER_REGISTRY-}hairhubapi
#     networks:
#       - demo
#     ports:
#       - "8080:80"
#     build:
#       context: .
#       dockerfile: Hairhub.API/Dockerfile
#     environment:
#       ASPNETCORE_URLS: http://+:80
#       ConnectionStrings__DefaultConnection: "Server=mssql-db;Database=HairHubDB;User Id=sa;Password=Admin@123;"
#       TZ: "Asia/Ho_Chi_Minh"
#     depends_on:
#       - mssql

# networks:
#   demo:
#     name: demo

# volumes:
#   mssql-data: 
#   mssql-log: 
#   mssql-secrets: 

# COMMANT

# version: '3.4'

# services:
#   mssql:
#     container_name: mssql-db-new  # Đổi tên container để tránh xung đột
#     hostname: mssql-db
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     user: root
#     networks:
#       - demo
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Admin@123
#       - MSSQL_PID=Developer
#       - MSSQL_TCP_PORT=1433
#       - TZ=Asia/Ho_Chi_Minh
#     ports:
#       - "1456:1433"
#     volumes:
#       - mssql-data:/var/opt/mssql/data
#       - mssql-log:/var/opt/mssql/log
#       - mssql-secrets:/var/opt/mssql/secrets

#   hairhub.api:
#     container_name: hairhub-api-new  # Đổi tên container để tránh xung đột
#     build:
#       context: .
#       dockerfile: Hairhub.API/Dockerfile
#     image: hairhubapi
#     networks:
#       - demo
#     ports:
#       - "8444:443"  # Cổng HTTPS
#       - "8085:80"   # Cổng HTTP (nếu cần)
#     environment:
#       - ASPNETCORE_URLS=https://+:443;http://+:80
#       - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=HairHubDB;User Id=sa;Password=Admin@123;
#       - ASPNETCORE_Kestrel__Certificates__Default__Password=Tien2002@
#       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#       - TZ=Asia/Ho_Chi_Minh
#     volumes:
#       - /var/docker/certs:/https:ro
#     depends_on:
#       - mssql

# networks:
#   demo:
#     driver: bridge

# volumes:
#   mssql-data: 
#   mssql-log: 
#   mssql-secrets:


version: '3.4'

services:
  mssql:
    container_name: mssql-db-new
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    networks:
      - demo
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1456:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets

  hairhub.api:
    container_name: hairhub-api-new
    build:
      context: .
      dockerfile: Hairhub.API/Dockerfile
    image: hairhubapi
    networks:
      - demo
    ports:
      - "8085:80"   # Cổng HTTP (dành cho nội bộ)
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=HairHubDB;User Id=sa;Password=Admin@123;
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - mssql

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/gahonghac.net:/etc/letsencrypt/live/gahonghac.net
    ports:
      - "8080:80"     
      - "8443:443"
    networks:
      - demo

networks:
  demo:
    driver: bridge

volumes:
  mssql-data: 
  mssql-log: 
  mssql-secrets:

