version: '3.4'
services:
   mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - demo
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets 
   hairhub.api:
    image: ${DOCKER_REGISTRY-}hairhubapi
    networks:
      - demo
    ports: 
      - "8080:80"
    build:
      context: .
      dockerfile: Hairhub.API/Dockerfile
    depends_on: 
      - mssql
networks:
    demo:
      name: demo
