name: Runner HairHub

on:
  push:
    branches:
      - master

jobs:
  DeployHairHub:
    runs-on: 
    - self-hosted
    - RunnerHairhub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HAIRHUB }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t hairhubapi:latest -f Hairhub.API/Dockerfile .
        docker tag hairhubapi:latest ${{ secrets.DOCKER_HAIRHUB }}/hairhubapi:latest
        docker push ${{ secrets.DOCKER_HAIRHUB }}/hairhubapi:latest

    - name: Deploy to server
      run: |
        docker pull ${{ secrets.DOCKER_HAIRHUB }}/hairhubapi:latest
        cd /root/actions-runner/RunnerHairhub/Back-end-HaiHub-Project/Back-end-HaiHub-Project
        docker compose up --build -d
