name: hairhub-runner

on:
  push:
    branches:
      - master

jobs:
  hellow-tien:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Run Docker compose command
      run: docker compose up --build -d
