name: hairhub-runner

on:
  push:
    branches:
      - deploy-backup

jobs:
  Deploy-Hairhub-Container:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove old containers
        run: docker compose down

      - name: Remove all old containers, images, and volumes
        run: |
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          docker rmi $(docker images -q) || true
          docker volume prune -f

      - name: Run Docker compose command
        run: |
          set -e
          docker compose up --build -d
