name: hairhub-runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Chạy job trên runner tự host, phù hợp với VPS của bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t hairhubapi:latest -f Hairhub.API/Dockerfile .
          docker tag hairhubapi:latest localhost/hairhubapi:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull localhost/hairhubapi:latest
            cd /root/actions-runner/RunnerHairhub/Back-end-HaiHub-Project/Back-end-HaiHub-Project
            docker-compose down
            docker-compose up -d
