name: hairhub-runner

on:
  push:
    branches:
      - deploy-backup

jobs:
  Deploy-Hairhub-Container:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove unused images, containers, and volumes
        run: |
          docker ps -aq --filter "name=hairhub-api-new" | xargs -r docker stop
          docker ps -aq --filter "name=hairhub-api-new" | xargs -r docker rm
          docker image prune -f
          docker volume ls -q | grep "hairhub-api" | xargs -r docker volume rm

      - name: Run Docker compose command
        run: |
          set -e
          docker compose up --build -d
